In [1]:
import numpy as np
import pandas as pd
from pathlib import Path

In [2]:
train_df = pd.read_csv(Path('Resources/2019loans.csv'))
test_df = pd.read_csv(Path('Resources/2020Q1loans.csv'))

In [7]:
# Convert categorical data to numeric and separate target feature for training data
X_train = pd.get_dummies(train_df.drop(columns=['loan_status']))
y_train = train_df['loan_status']
X_train.head(20)

,Unnamed: 0,index,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,...,verification_status_Verified,pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y,debt_settlement_flag_N,debt_settlement_flag_Y
0,57107,57107,13375.0,0.1797,483.34,223000.0,29.99,0.0,0.0,15.0,...,0,1,0,1,1,0,1,0,1,0
1,141451,141451,21000.0,0.1308,478.68,123000.0,11.26,2.0,0.0,16.0,...,0,1,0,1,1,0,1,0,1,0
2,321143,321143,20000.0,0.1240,448.95,197000.0,11.28,0.0,0.0,12.0,...,0,1,0,1,1,0,1,0,1,0
3,11778,11778,3000.0,0.1240,100.22,45000.0,18.08,0.0,0.0,12.0,...,0,1,0,1,1,0,1,0,1,0
4,169382,169382,30000.0,0.1612,1056.49,133000.0,27.77,0.0,2.0,13.0,...,0,1,0,1,1,0,1,0,1,0
5,31295,31295,6500.0,0.1614,228.98,65000.0,27.49,1.0,0.0,9.0,...,0,1,0,1,1,0,1,0,1,0
6,173238,173238,40000.0,0.1240,897.89,171000.0,20.74,0.0,0.0,9.0,...,0,1,0,1,1,0,1,0,1,0
7,116755,116755,5000.0,0.1719,178.74,55000.0,10.80,1.0,0.0,5.0,...,0,1,0,1,1,0,1,0,1,0
8,170311,170311,6000.0,0.1102,196.49,36000.0,27.28,0.0,0.0,19.0,...,0,1,0,1,1,0,1,0,1,0
9,254794,254794,10625.0,0.1102,347.95,73000.0,7.09,0.0,2.0,18.0,...,0,1,0,1,1,0,1,0,1,0
10,38248,38248,22625.0,0.0702,698.81,75000.0,34.86,0.0,0.0,5.0,...,1,1,0,1,0,1,1,0,1,0
11,32758,32758,8000.0,0.1614,281.81,29000.0,24.63,0.0,0.0,10.0,...,0,1,0,1,1,0,1,0,1,0
12,248585,248585,35000.0,0.0756,1089.69,90000.0,27.75,0.0,0.0,22.0,...,0,1,0,1,1,0,1,0,1,0
13,79308,79308,4800.0,0.0819,150.84,40000.0,23.01,0.0,0.0,10.0,...,0,1,0,1,1,0,1,0,1,0
14,22954,22954,11000.0,0.0881,348.83,85000.0,12.76,0.0,1.0,4.0,...,0,1,0,1,1,0,1,0,1,0
15,163076,163076,28000.0,0.0881,578.66,155000.0,9.45,3.0,0.0,14.0,...,0,1,0,1,1,0,1,0,1,0
16,15902,15902,7500.0,0.1033,243.17,41000.0,27.59,0.0,1.0,13.0,...,0,1,1,0,1,0,1,0,1,0
17,1655,1655,10000.0,0.1557,349.46,98000.0,5.56,0.0,0.0,9.0,...,0,1,1,0,1,0,1,0,1,0
18,38852,38852,12850.0,0.1447,442.13,40000.0,21.00,0.0,0.0,9.0,...,1,1,1,0,1,0,1,0,1,0
19,310148,310148,37000.0,0.1033,792.17,98600.0,29.69,0.0,1.0,13.0,...,0,1,0,1,1,0,1,0,1,0

In [12]:
# Convert categorical data to numeric and separate target feature for testing data
X_test = pd.get_dummies(test_df.drop(columns=['loan_status']))
y_test = test_df['loan_status']

In [13]:
# add missing dummy variables to testing set
for col in X_train.columns:
    if col not in X_test.columns: 
        X_test[col]=0

In [17]:
# Train the Logistic Regression model on the unscaled data and print the model score
from sklearn.linear_model import LogisticRegression
classifier=  LogisticRegression()
classifier.fit (X_train, y_train)
classifier.score (X_test,y_test)

C:\Users\aksah\anaconda\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.5253083794130158

In [20]:
# Train a Random Forest Classifier model and print the model score
from sklearn.ensemble import RandomForestClassifier
classifier= RandomForestClassifier()
classifier.fit(X_train,y_train)
classifier.score (X_test,y_test)

0.628668651637601

In [23]:
# Scale the data
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
scalar.fit (X_train)
X_train_scaled=scalar.transform(X_train)
X_test_scaled=scalar.transform(X_test)

In [24]:
# Train the Logistic Regression model on the scaled data and print the model score
classifier=  LogisticRegression()
classifier.fit (X_train_scaled, y_train)
classifier.score (X_test_scaled,y_test)

C:\Users\aksah\anaconda\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.7201190982560612

In [26]:
# Train a Random Forest Classifier model on the scaled data and print the model score
classifier = RandomForestClassifier()
classifier.fit(X_train_scaled, y_train)
classifier.score(X_test_scaled, y_test)

0.5969800085070183